### ISSUE TITLE
Windows 11 家庭中文版 64位操作系统 版本号：23H2 >>使用不了fs_64.exe

### ISSUE THREAD

**Issue by 69LTZ** [P001water/fs#2]
尝试了fs_64.exe和fs_86.exe都显示与Windows版本不兼容。是因为博主的fs就是不兼容win11吗？
<img width="865" alt="屏幕截图 2024-06-20 143406" src="https://github.com/P001water/fs/assets/125969498/ffcaa32d-7499-4ef8-a41c-a8f16dd14228">

**Comment by P001water** [comment]
win11是能跑的，大概率是因为你是家庭版，没开程序兼容

**Comment by 69LTZ** [comment]
好吧。那解决办法就只能重装系统了呀

**Comment by P001water** [comment]
手动开个程序兼容应该也行
