### ISSUE TITLE
socks5代理功能貌似用不了

### ISSUE THREAD

**Issue by loach2020** [P001water/fs#3]
![图片](https://github.com/P001water/fs/assets/24237744/2b6a2a0c-80d6-4855-bf10-46d83addba4a)
![图片](https://github.com/P001water/fs/assets/24237744/ad2b710c-0f2d-4332-a42f-9e952acb8a59)

**Comment by P001water** [comment]
有这个问题，改了运行逻辑的bug，后面补上

**Comment by P001water** [comment]
已修复 见 releases/fs_0.0.1
